### ISSUE TITLE
Yocto version being used?

### ISSUE THREAD

**Issue by Hussain1811** [agl-ic-eg/meta-agl#2]
May i know which yocto version is being used currently as part of the build process for AGL?
Anywhere mentioned in the documentation?

**Comment by harunobukurokawa** [comment]
If you want to build original AGL UCB, please refer here [1]

Do you want this IC-EG's trial meta-agl ?

[1] https://docs.automotivelinux.org/en/master/#0_Getting_Started/2_Building_AGL_Image/2_Downloading_AGL_Software/

**Comment by Hussain1811** [comment]
Actually i just wanted to know which yocto version is used in AGL
3.1 (Dunfell)/3.2/3.3/3.4?

**Comment by harunobukurokawa** [comment]
The latest AGL UCB (11.0.x/koi) use dunfell [2] 
You can find the some information from AGL's wiki.

Here is not main documentation.

[2] https://wiki.automotivelinux.org/agl-distro/release-notes#kooky_koi

**Comment by Hussain1811** [comment]
Thanks for the link :)
